server:
  port:8080

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
   #  url: jdbc:mysql://132.126.3.51:3306/test
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath*:com/sun/mapper/*SqlMapper.xml

